package com.travelbuddy.ui.theme

import androidx.compose.ui.graphics.Color

// Warm horizon / terracotta–sage palette: sunset warmth + grounded teal for trust (not default blue).

val md_theme_light_primary = Color(0xFF8B4F3C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD4)
val md_theme_light_onPrimaryContainer = Color(0xFF410E06)

val md_theme_light_secondary = Color(0xFF3E5F57)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFBEE0D6)
val md_theme_light_onSecondaryContainer = Color(0xFF08201A)

val md_theme_light_tertiary = Color(0xFF6E5F2F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF7E2A9)
val md_theme_light_onTertiaryContainer = Color(0xFF251A00)

val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)

val md_theme_light_background = Color(0xFFFFF8F5)
val md_theme_light_onBackground = Color(0xFF1E1B18)
val md_theme_light_surface = Color(0xFFFFFBF7)
val md_theme_light_onSurface = Color(0xFF1E1B18)
val md_theme_light_surfaceVariant = Color(0xFFF0E7E2)
val md_theme_light_onSurfaceVariant = Color(0xFF53433D)
val md_theme_light_outline = Color(0xFF85736C)
val md_theme_light_outlineVariant = Color(0xFFD7C7BF)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF36302C)
val md_theme_light_inverseOnSurface = Color(0xFFFCEEE8)
val md_theme_light_inversePrimary = Color(0xFFFFB4A4)
val md_theme_light_surfaceTint = Color(0xFF8B4F3C)
val md_theme_light_surfaceBright = Color(0xFFFFF8F5)
val md_theme_light_surfaceDim = Color(0xFFE0D8D3)
val md_theme_light_surfaceContainer = Color(0xFFF7EFEA)
val md_theme_light_surfaceContainerHigh = Color(0xFFF1E7E1)
val md_theme_light_surfaceContainerHighest = Color(0xFFEBE1DB)
val md_theme_light_surfaceContainerLow = Color(0xFFFFF8F5)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)

val md_theme_dark_primary = Color(0xFFFFB4A4)
val md_theme_dark_onPrimary = Color(0xFF5F1706)
val md_theme_dark_primaryContainer = Color(0xFF7C2E1A)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD4)

val md_theme_dark_secondary = Color(0xFFA2D0C4)
val md_theme_dark_onSecondary = Color(0xFF0D3129)
val md_theme_dark_secondaryContainer = Color(0xFF28473F)
val md_theme_dark_onSecondaryContainer = Color(0xFFBEE0D6)

val md_theme_dark_tertiary = Color(0xFFD9C78E)
val md_theme_dark_onTertiary = Color(0xFF392F0C)
val md_theme_dark_tertiaryContainer = Color(0xFF554619)
val md_theme_dark_onTertiaryContainer = Color(0xFFF7E2A9)

val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)

val md_theme_dark_background = Color(0xFF141210)
val md_theme_dark_onBackground = Color(0xFFF0E7E2)
val md_theme_dark_surface = Color(0xFF1C1917)
val md_theme_dark_onSurface = Color(0xFFF0E7E2)
val md_theme_dark_surfaceVariant = Color(0xFF53433D)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C7BF)
val md_theme_dark_outline = Color(0xFFA08C83)
val md_theme_dark_outlineVariant = Color(0xFF53433D)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFF0E7E2)
val md_theme_dark_inverseOnSurface = Color(0xFF36302C)
val md_theme_dark_inversePrimary = Color(0xFF8B4F3C)
val md_theme_dark_surfaceTint = Color(0xFFFFB4A4)
val md_theme_dark_surfaceBright = Color(0xFF3B3531)
val md_theme_dark_surfaceDim = Color(0xFF141210)
val md_theme_dark_surfaceContainer = Color(0xFF221F1D)
val md_theme_dark_surfaceContainerHigh = Color(0xFF2D2825)
val md_theme_dark_surfaceContainerHighest = Color(0xFF383330)
val md_theme_dark_surfaceContainerLow = Color(0xFF1C1917)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0E0C0B)
